### ISSUE TITLE
(stastsd) not wokring idle slot with latest llama.cpp

### ISSUE THREAD

**Issue by bodybreaker** [distantmagic/paddler#19]
paddler_slots_idle not working with lastest llama.cpp

**Comment by us58** [comment]
The slot states were moved from the /health endpoint to a new /slots endpoint. See [https://github.com/ggerganov/llama.cpp/pull/9056](https://github.com/ggerganov/llama.cpp/pull/9056).

**Comment by mcharytoniuk** [comment]
@us58 Thanks for letting me know.

**Comment by mcharytoniuk** [comment]
@bodybreaker @us58 I released a new version that uses the new `/slots` endpoint from llama.cpp server: https://github.com/distantmagic/paddler/releases/tag/v0.7.0

Please let me know if that solved StatsD issue.

**Comment by debrisapron** [comment]
I think I might be having a problem related to this. In my llama.cpp logs I see the monitoring requests coming in from the paddler agent, but they're still coming into the `/health` endpoint instead of the `/slots` endpoint as they should be. This is with release 0.8.0 so as I understand it this should be working?

**Comment by mcharytoniuk** [comment]
@debrisapron @bodybreaker  I have just released a new stable version of Paddler (`v1.0.0`) and changed the CLI framework, overall it underwent a total rewrite. 

I think your issue should be solved now, if it still persists feel free to reopen (please check the README though, some flag names have changed).
