### ISSUE TITLE
Is it possible to deploy more than 1 balancer?

### ISSUE THREAD

**Issue by wwulfric** [distantmagic/paddler#9]
The llama-server stat is stored in balancer memory. It seems not work for multiple balancers

**Comment by mcharytoniuk** [comment]
@wwulfric  I did not add a shared state feature (through some external storage) because I did not need it yet, but I am all for it if there is a demand.

Do you ask because you need high availability or because you exhausted all the server resources?

If you need high availability, I would approach that similarly to how you would deploy HAProxy (an additional standby instance that starts to accept traffic if a primary Paddler instance fails).

**Comment by wwulfric** [comment]
@mcharytoniuk Thank you. I am just concerned about the high availability issue.

**Comment by mcharytoniuk** [comment]
> @mcharytoniuk Thank you. I am just concerned about the high availability issue.

No problem. In that case, I'd recommend using [keepalived](https://www.keepalived.org/) in front of Paddler, combined with a redundant Paddler instance on standby.
